[package]
name = "sherlock-clipvault"
version = "0.1.0"
edition = "2024"

[dependencies]
fancy-regex = "0.17.0"
image = "0.25.9"
rayon = "1.11.0"
regex = "1.12.2"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
